In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
Dataset = pd.read_csv("Social_Network_Ads.csv")

In [4]:
print(Dataset)

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]


In [5]:
Dataset.drop(["User ID"],axis=1)

Gender  Age  EstimatedSalary  Purchased
0      Male   19            19000          0
1      Male   35            20000          0
2    Female   26            43000          0
3    Female   27            57000          0
4      Male   19            76000          0
..      ...  ...              ...        ...
395  Female   46            41000          1
396    Male   51            23000          1
397  Female   50            20000          1
398    Male   36            33000          0
399  Female   49            36000          1

[400 rows x 4 columns]

In [35]:
X = Dataset.iloc[:,[2,3]].values
y = Dataset.iloc[:,[4]].values

In [36]:
from sklearn.cluster import KMeans 
from sklearn.model_selection import train_test_split

In [37]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.45,random_state=0)

In [38]:
from sklearn.preprocessing import StandardScaler

In [47]:
sc = StandardScaler()
X_train=sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [48]:
kmeans = KMeans(n_clusters = 5, init = 'k-means++',  max_iter = 300 , n_init=10, random_state = 0)

In [49]:
kmeans.fit(X_train,y_train)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=5, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=0, tol=0.0001, verbose=0)

In [50]:
y_pred = kmeans.predict(X_test)

In [51]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [52]:
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[ 4 34 30  2 42]
 [21  7  0 31  9]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]]


In [54]:
accuracy = accuracy_score(y_test,y_pred)
print(accuracy)

0.06111111111111111
